### ISSUE TITLE
Preserve Cookies of VK Login Session between Runs?

### ISSUE THREAD

**Issue by gnull** [grwlf/vkhs#14]
Can VKHS save cookies of VK session during login and reuse them to obtain a new access-token when the old one expires? Like it does with access token?

It seemed obvious to me that if such feature exists, there must be a field related to it somewhere in `GenericOptions` (e.g. `l_cookies_file` analogous to `l_access_token_file`), but I didn't find any.

Ivan

**Comment by sergei-mironov** [comment]
No support for this at the moment. Probably that is because I didn't need non-empty cookies before. What is the most common situation when they are required?

It shouldn't be hard to add. As I see, one should replace calls to `cookiesCreate ()` with the state reads here and there, and also dump the returned cookies after responses. I'll place this task on my todo list. Also I'll be glad to accept this contribution from elsewhere.

**Comment by gnull** [comment]
Logging in at each run of an application (or once every 24 hours when access token expires) might be inconvenient because Vkontakte will send you email notifications of each login, resulting in a flood of messages if logins are too frequent. (This may depend on your security settings at Vkontakte.) Also, it seems like a typical behaviour of other Vkontakte clients (e.g. the official android app or Kate Mobile) to reuse the session which was obtained only once.

I might work on this feature myself during the next few weeks. Thanks for the directions!

**Comment by sergei-mironov** [comment]
That would be great!
