### ISSUE TITLE
Installation with Stack?

### ISSUE THREAD

**Issue by dniku** [grwlf/vkhs#9]
Disclaimer: I'm new to the Haskell ecosystem.

I've tried to install `VKHS` using `stack` instead of `cabal` and it failed with unresolved dependencies.

```
$ stack install VKHS
Populated index cache.    
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package EitherT in known packages

--  Failure when adding dependencies:    
      EitherT: needed (-any), not present in build plan (latest applicable is 0.2.0)
      regexpr: needed (-any), not present in build plan (latest applicable is 0.5.4)
    needed for package: VKHS-1.6.1

--  While attempting to add dependency,
    Could not find package regexpr in known packages

Recommended action: try adding the following to your extra-deps in /path/to/current/directory/stack.yaml
- EitherT-0.2.0
- regexpr-0.5.4

You may also want to try the 'stack solver' command
```

I don't understand these error messages. What exactly failed and can I fix it?

**Comment by sergei-mironov** [comment]
Oops, more than a year.. I dont use stack regularly. Probably, the problem was about two packages which were missing from default collection (or build plan, how do they call it?). Stack has an option of adding additional packages just for situations like this. Try editing this `stack.yaml` file, it should be created in toplevel project directory.

**Comment by gnull** [comment]
@Pastafarianist,

I have built VKHS using `stack` once, you may find some helpful info in my fork gnull@6dff370546f0c516e05ae6b7e86ad83d9eb76abd. This commit adds a working `stack.yaml` into the project and its message describes what I did to obtain it.

Although @grwlf, has made some changes to https://github.com/grwlf/vkhs/commit/master since I made that gnull@6dff370546f0c516e05ae6b7e86ad83d9eb76abd commit, I think the `stack.yaml` contained there should also work if you merge it into the current master. (But I didn't check whether it does or not.)
